# Generated by Django 5.2.7 on 2025-11-04 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('cantidad_asientos', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('ACT', 'Activa'), ('MAN', 'En Mantenimiento'), ('INA', 'Inactiva')], default='ACT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='recorrido_default', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('TER', 'Estación Terminal')], default='TER', max_length=3)),
                ('destino', models.CharField(choices=[('BAL', 'Balcozna'), ('ROD', 'El Rodeo'), ('GRU', 'La Gruta')], max_length=3)),
                ('puntos_destacados', models.ManyToManyField(blank=True, related_name='recorridos', to='citytour.puntodestacado')),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=200)),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citytour.recorrido')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citytour.recorrido')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodoPago', models.CharField(max_length=100)),
                ('itinerario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='citytour.itinerario')),
            ],
        ),
    ]
