# Generated by Django 5.2.6 on 2025-10-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0007_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='puntos/')),
            ],
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('TER', 'Estación Terminal')], default='TER', max_length=3)),
                ('destino', models.CharField(choices=[('BAL', 'Balcozna'), ('ROD', 'El Rodeo'), ('GRU', 'La Gruta')], max_length=3)),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('cantidad_asientos', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('ACT', 'Activa'), ('MAN', 'En Mantenimiento'), ('INA', 'Inactiva')], default='ACT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=200)),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citytour.recorrido')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodoPago', models.CharField(max_length=100)),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citytour.recorrido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='recorrido',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citytour.unidad'),
        ),
    ]
