# Generated by Django 5.2.6 on 2025-11-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrido',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recorrido',
            name='nombre',
            field=models.CharField(default='recorrido_default', max_length=100),
        ),
    ]
