# Generated by Django 5.2.6 on 2025-11-03 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytour', '0002_recorrido_descripcion_recorrido_nombre'),
        ('usuario', '0009_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='recorrido',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario'),
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='citytour.recorrido')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='itinerario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='citytour.itinerario'),
        ),
    ]
