# Generated by Django 5.2.6 on 2025-11-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytour', '0003_remove_reserva_recorrido_alter_reserva_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorrido',
            name='puntos_destacados',
            field=models.ManyToManyField(blank=True, related_name='recorridos', to='citytour.puntodestacado'),
        ),
    ]
