# Generated by Django 5.2.6 on 2025-11-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytour', '0004_recorrido_puntos_destacados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntodestacado',
            name='imagen',
        ),
        migrations.AddField(
            model_name='puntodestacado',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
