# Generated by Django 5.2.6 on 2025-11-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citytour', '0005_remove_puntodestacado_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recorrido',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='recorrido',
            name='hora_salida',
        ),
    ]
