# Generated by Django 5.2.7 on 2025-10-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('cantidad_asientos', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('ACT', 'Activa'), ('MAN', 'En Mantenimiento'), ('INA', 'Inactiva')], default='ACT', max_length=3)),
            ],
        ),
    ]
