# Generated by Django 5.2.7 on 2025-10-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('dni', models.PositiveBigIntegerField(unique=True)),
                ('rol', models.CharField(choices=[('Administrador', 'ADMIN'), ('TURISTA', 'Turista'), ('OPERADOR', 'Operador')], default='TURISTA', max_length=20)),
            ],
        ),
    ]
