# Generated by Django 5.2.7 on 2025-10-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'ADMIN'), ('TURISTA', 'Turista'), ('Operador', 'OPERADOR')], default='TURISTA', max_length=20),
        ),
    ]
