# Generated by Django 5.2.6 on 2025-10-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('TURISTA', 'Turista'), ('OPERADOR', 'Operador')], default='TURISTA', max_length=20),
        ),
    ]
