# Generated by Django 5.2.6 on 2025-11-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('TURISTA', 'Turista'), ('Operador', 'OPERADOR')], default='TURISTA', max_length=20),
        ),
    ]
