# Generated by Django 5.2.6 on 2025-11-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('Turista', 'TURISTA'), ('Operador', 'OPERADOR')], default='TURISTA', max_length=20),
        ),
    ]
