# Generated by Django 5.2.7 on 2025-10-15 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('TER', 'Estación Terminal')], default='TER', max_length=3)),
                ('destino', models.CharField(choices=[('BAL', 'Balcozna'), ('ROD', 'El Rodeo'), ('GRU', 'La Gruta')], max_length=3)),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidades.unidad')),
            ],
        ),
    ]
