# Generated by Django 5.2.7 on 2025-10-15 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recorridos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=200)),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recorridos.recorrido')),
            ],
        ),
    ]
